version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: booklogix-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - booklogix
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: booklogix-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/src/env/.env.production
    environment:
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - booklogix
    restart: unless-stopped

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    container_name: booklogix-mongo
    networks:
      - booklogix
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  booklogix:
    driver: bridge
