version: "3.8"

services:
  frontend:
    image: mparmilan/booklogix-frontend:latest
    ports:
      - "3020:3001"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - bookshop
    restart: unless-stopped

  backend:
    image: mparmilan/booklogix-backend:latest
    ports:
      - "5001:5000"
    env_file:
      - ./backend/src/env/.env.production
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongo:27017/book_prod?authSource=admin
    depends_on:
      - mongo
    networks:
      - bookshop
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: book_prod
    volumes:
      - mongo-data:/data/db
    networks:
      - bookshop
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongo-data:

networks:
  bookshop:
    driver: bridge
