version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - bookshop
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - bookshop
    restart: unless-stopped

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - bookshop
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
