name: Deploy Frontend to Docker Hub

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
    branches: [release-1.0]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image (frontend)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bookshop-frontend:latest ./frontend

      - name: Push to Docker Hub (frontend)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bookshop-frontend:latest

      - name: ✅ Deployment Successful
        run: echo "🎉 Docker image for frontend pushed successfully to Docker Hub!"
